<?php

$title = 'Ajouter un nouveau média';
$this->headTitle($title);
?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(null, array('controller' => 'index', 'action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('desc'));
echo $this->formRow($form->get('link'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();